### ISSUE TITLE
Button Get me a Coffee

### ISSUE THREAD

**Issue by Aygotori** [tikismoke/home-assistant-nespressoble#8]
Hello there!

Nice work on this integration! Thanks a lot ! 
But how can i put the button "Make a Coffee" in Lovelace? ^^ 
I only have the sensors...

**Comment by tikismoke** [comment]
Did you use the python script with mqtt or the ha integration?

**Comment by Aygotori** [comment]
I only get the ha integration to work with all the sensors... 
I saw the python script but dont know how to use it...

Thanks for your reply,

**Comment by tikismoke** [comment]
Ok in theory... The ha integration has the button as service if I remember what I've done.

**Comment by Aygotori** [comment]
You're right! I can call the service (it works!) but i cannot get a button to work =/ 
I have this config for a button:

```
type: button
name: Make a coffee
show_state: true
icon: 'hass:coffee'
tap_action:
  action: call-service
  service: nespresso.coffee
  data:
    mac: 'd1:86:08:5d:50:f3'
```

But this doesn't work. Am i missing something?
